### ISSUE TITLE
crash when tapping multiple times in 'Tap anywhere to restart' screen

### ISSUE THREAD

**Issue by EitanZilcha** [PCOffline/Spaceship#2]
crash when tapping multiple times in 'Tap anywhere to restart' screen

crash when tapping multiple times in 'Tap anywhere to restart' screen

**Comment by PCOffline** [comment]
Does it happen specifically after losing, winning or after both? Does it always happen, or does it happen only sometimes? Are there any other conditions that I need to know of in order to reproduce this bug? Try to be as specific and informative as possible.

**Comment by PCOffline** [comment]
I don't know

**Comment by PCOffline** [comment]
Fixed with Version 0.9!
